name: Deploy Frontend
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t cygnetops/react-test -f Dockerfile.dev .
        run: docker run -e CI=true cygnetops/react-test npm test